#ifndef GUARD_GENERATED_ANIM_CODE_IndoorForest_H
#define GUARD_GENERATED_ANIM_CODE_IndoorForest_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame0[] = INCBIN_U16("data/tilesets/primary/indoor_forest/porytiles_bin/anim/flowers/0.4bpp");
const u16 gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame1[] = INCBIN_U16("data/tilesets/primary/indoor_forest/porytiles_bin/anim/flowers/1.4bpp");
const u16 gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame2[] = INCBIN_U16("data/tilesets/primary/indoor_forest/porytiles_bin/anim/flowers/2.4bpp");
const u16 gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame3[] = INCBIN_U16("data/tilesets/primary/indoor_forest/porytiles_bin/anim/flowers/3.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_IndoorForest_Flowers[] = {
    gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame0,
    gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame1,
    gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame2,
    gTilesetAnims_PorytilesManaged_IndoorForest_Flowers_Frame3
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_IndoorForest_Flowers(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_IndoorForest_Flowers);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_IndoorForest_Flowers[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(1)), 4 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_IndoorForest(u16 timer)
{
    if (timer % 32 == 0)
    {
        QueueAnimTiles_PorytilesManaged_IndoorForest_Flowers(timer / 32);
    }
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_IndoorForest(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_IndoorForest;
}

#endif // GUARD_GENERATED_ANIM_CODE_IndoorForest_H
